from django.core.management import BaseCommand

from main.models import Student


class Command(BaseCommand):
    def handle(self, *args, **options):
        students=[{"id":1,"first_name":"Sydel","last_name":"Lappine","email":"slappine0@yellowbook.com","dob":"2006-10-26","gender":"Female"},
{"id":2,"first_name":"Daryl","last_name":"Emby","email":"demby1@amazon.com","dob":"2006-03-30","gender":"Female"},
{"id":3,"first_name":"Valma","last_name":"Castard","email":"vcastard2@bandcamp.com","dob":"2004-05-23","gender":"Female"},
{"id":4,"first_name":"Constanta","last_name":"Dee","email":"cdee3@ovh.net","dob":"2005-10-11","gender":"Female"},
{"id":5,"first_name":"Noah","last_name":"Belly","email":"nbelly4@blogs.com","dob":"2005-12-27","gender":"Male"},
{"id":6,"first_name":"Yetta","last_name":"Halpen","email":"yhalpen5@merriam-webster.com","dob":"2005-12-19","gender":"Female"},
{"id":7,"first_name":"Cart","last_name":"Cohan","email":"ccohan6@army.mil","dob":"2005-10-19","gender":"Male"},
{"id":8,"first_name":"Robbi","last_name":"Bayfield","email":"rbayfield7@elpais.com","dob":"2004-08-16","gender":"Female"},
{"id":9,"first_name":"Alyssa","last_name":"Hoble","email":"ahoble8@rakuten.co.jp","dob":"2000-12-10","gender":"Female"},
{"id":10,"first_name":"Moises","last_name":"Kyrkeman","email":"mkyrkeman9@booking.com","dob":"2001-06-25","gender":"Male"},
{"id":11,"first_name":"Linnie","last_name":"Fawdrie","email":"lfawdriea@globo.com","dob":"2006-09-22","gender":"Female"},
{"id":12,"first_name":"Ethelin","last_name":"Sey","email":"eseyb@parallels.com","dob":"2003-02-14","gender":"Female"},
{"id":13,"first_name":"Abe","last_name":"Stoffler","email":"astofflerc@uiuc.edu","dob":"2004-01-02","gender":"Male"},
{"id":14,"first_name":"Caleb","last_name":"Joderli","email":"cjoderlid@theglobeandmail.com","dob":"2003-01-06","gender":"Male"},
{"id":15,"first_name":"Holly-anne","last_name":"Chishull","email":"hchishulle@webmd.com","dob":"2005-05-30","gender":"Female"},
{"id":16,"first_name":"Reinhard","last_name":"Lillico","email":"rlillicof@toplist.cz","dob":"2002-08-24","gender":"Male"},
{"id":17,"first_name":"Boniface","last_name":"Cawtheray","email":"bcawtherayg@answers.com","dob":"2002-04-16","gender":"Male"},
{"id":18,"first_name":"Antonia","last_name":"Stammler","email":"astammlerh@ucoz.com","dob":"2004-04-06","gender":"Female"},
{"id":19,"first_name":"Jana","last_name":"Franciskiewicz","email":"jfranciskiewiczi@sun.com","dob":"2003-10-25","gender":"Female"},
{"id":20,"first_name":"Clifford","last_name":"Stappard","email":"cstappardj@jimdo.com","dob":"2006-10-10","gender":"Male"},
{"id":21,"first_name":"Celestina","last_name":"Padmore","email":"cpadmorek@arizona.edu","dob":"2002-05-28","gender":"Female"},
{"id":22,"first_name":"August","last_name":"Koppe","email":"akoppel@github.com","dob":"2005-07-27","gender":"Male"},
{"id":23,"first_name":"Rosa","last_name":"Frizell","email":"rfrizellm@hugedomains.com","dob":"2005-12-13","gender":"Female"},
{"id":24,"first_name":"Leilah","last_name":"Cobelli","email":"lcobellin@samsung.com","dob":"2004-03-10","gender":"Female"},
{"id":25,"first_name":"Aveline","last_name":"Tabary","email":"atabaryo@thetimes.co.uk","dob":"2003-07-03","gender":"Female"},
{"id":26,"first_name":"Hildegaard","last_name":"Alejandro","email":"halejandrop@plala.or.jp","dob":"2001-10-06","gender":"Female"},
{"id":27,"first_name":"Camey","last_name":"MacNess","email":"cmacnessq@weebly.com","dob":"2002-12-06","gender":"Male"},
{"id":28,"first_name":"Ferrel","last_name":"Elks","email":"felksr@intel.com","dob":"2006-11-12","gender":"Male"},
{"id":29,"first_name":"Hester","last_name":"Levene","email":"hlevenes@feedburner.com","dob":"2003-08-05","gender":"Female"},
{"id":30,"first_name":"Laverne","last_name":"Mulheron","email":"lmulheront@mozilla.org","dob":"2005-01-24","gender":"Female"},
{"id":31,"first_name":"Mallory","last_name":"Rumble","email":"mrumbleu@theguardian.com","dob":"2001-07-01","gender":"Male"},
{"id":32,"first_name":"Josefina","last_name":"Knights","email":"jknightsv@wordpress.com","dob":"2005-08-21","gender":"Female"},
{"id":33,"first_name":"Minetta","last_name":"Beaconsall","email":"mbeaconsallw@reddit.com","dob":"2000-12-20","gender":"Female"},
{"id":34,"first_name":"Drucie","last_name":"Richards","email":"drichardsx@nih.gov","dob":"2001-10-06","gender":"Female"},
{"id":35,"first_name":"Marcella","last_name":"Sevitt","email":"msevitty@oakley.com","dob":"2001-07-05","gender":"Female"},
{"id":36,"first_name":"Franny","last_name":"Fealty","email":"ffealtyz@spotify.com","dob":"2004-12-02","gender":"Female"},
{"id":37,"first_name":"Ambrosi","last_name":"Fike","email":"afike10@fotki.com","dob":"2005-05-25","gender":"Male"},
{"id":38,"first_name":"Conny","last_name":"Barajas","email":"cbarajas11@about.com","dob":"2003-02-19","gender":"Male"},
{"id":39,"first_name":"Esma","last_name":"Sineath","email":"esineath12@tinypic.com","dob":"2003-03-08","gender":"Female"},
{"id":40,"first_name":"Isadora","last_name":"Spyvye","email":"ispyvye13@deviantart.com","dob":"2004-10-15","gender":"Female"},
{"id":41,"first_name":"Winn","last_name":"Fawlo","email":"wfawlo14@ucoz.ru","dob":"2004-11-08","gender":"Male"},
{"id":42,"first_name":"Sayres","last_name":"Giabucci","email":"sgiabucci15@disqus.com","dob":"2003-02-28","gender":"Male"},
{"id":43,"first_name":"Humphrey","last_name":"Stockle","email":"hstockle16@examiner.com","dob":"2006-07-22","gender":"Male"},
{"id":44,"first_name":"Alick","last_name":"Lasslett","email":"alasslett17@1688.com","dob":"2002-03-12","gender":"Male"},
{"id":45,"first_name":"Wally","last_name":"Sleath","email":"wsleath18@desdev.cn","dob":"2003-12-13","gender":"Male"},
{"id":46,"first_name":"Desi","last_name":"Fance","email":"dfance19@xrea.com","dob":"2001-12-28","gender":"Male"},
{"id":47,"first_name":"Tait","last_name":"Negal","email":"tnegal1a@japanpost.jp","dob":"2001-08-03","gender":"Male"},
{"id":48,"first_name":"Diana","last_name":"Ellett","email":"dellett1b@about.com","dob":"2005-06-07","gender":"Female"},
{"id":49,"first_name":"Tabbatha","last_name":"Capeling","email":"tcapeling1c@naver.com","dob":"2006-08-11","gender":"Female"},
{"id":50,"first_name":"Farlay","last_name":"Copestick","email":"fcopestick1d@baidu.com","dob":"2006-11-24","gender":"Male"},
{"id":51,"first_name":"Dukie","last_name":"Otto","email":"dotto1e@skype.com","dob":"2002-09-29","gender":"Male"},
{"id":52,"first_name":"Miriam","last_name":"Humphris","email":"mhumphris1f@ihg.com","dob":"2000-12-05","gender":"Female"},
{"id":53,"first_name":"Gwenora","last_name":"Bolter","email":"gbolter1g@ucoz.ru","dob":"2004-11-04","gender":"Female"},
{"id":54,"first_name":"Laughton","last_name":"Fantini","email":"lfantini1h@diigo.com","dob":"2005-12-24","gender":"Male"},
{"id":55,"first_name":"Floria","last_name":"Ugoni","email":"fugoni1i@timesonline.co.uk","dob":"2006-10-10","gender":"Female"},
{"id":56,"first_name":"Zerk","last_name":"Harburtson","email":"zharburtson1j@ca.gov","dob":"2005-09-13","gender":"Male"},
{"id":57,"first_name":"Ludvig","last_name":"Ligertwood","email":"lligertwood1k@hostgator.com","dob":"2006-03-20","gender":"Male"},
{"id":58,"first_name":"Doll","last_name":"Rattenbury","email":"drattenbury1l@google.co.jp","dob":"2006-08-13","gender":"Female"},
{"id":59,"first_name":"Hugh","last_name":"Stebles","email":"hstebles1m@cnn.com","dob":"2002-11-22","gender":"Male"},
{"id":60,"first_name":"Maura","last_name":"Brissard","email":"mbrissard1n@tamu.edu","dob":"2003-07-30","gender":"Female"},
{"id":61,"first_name":"Garner","last_name":"Buist","email":"gbuist1o@artisteer.com","dob":"2001-04-18","gender":"Male"},
{"id":62,"first_name":"Kipper","last_name":"Ragot","email":"kragot1p@google.nl","dob":"2003-02-08","gender":"Male"},
{"id":63,"first_name":"Shep","last_name":"Cleugh","email":"scleugh1q@bbb.org","dob":"2002-01-13","gender":"Male"},
{"id":64,"first_name":"Nikolai","last_name":"Herculson","email":"nherculson1r@ed.gov","dob":"2003-11-27","gender":"Male"},
{"id":65,"first_name":"Malissia","last_name":"Linguard","email":"mlinguard1s@friendfeed.com","dob":"2004-06-10","gender":"Female"},
{"id":66,"first_name":"Colet","last_name":"Hulle","email":"chulle1t@ibm.com","dob":"2002-05-16","gender":"Male"},
{"id":67,"first_name":"Marcille","last_name":"Girodon","email":"mgirodon1u@dailymotion.com","dob":"2002-09-25","gender":"Female"},
{"id":68,"first_name":"Care","last_name":"Deluce","email":"cdeluce1v@usa.gov","dob":"2004-02-18","gender":"Male"},
{"id":69,"first_name":"Biron","last_name":"Izakov","email":"bizakov1w@marketwatch.com","dob":"2006-07-19","gender":"Male"},
{"id":70,"first_name":"Fremont","last_name":"Juan","email":"fjuan1x@multiply.com","dob":"2001-08-06","gender":"Male"},
{"id":71,"first_name":"Kore","last_name":"Obert","email":"kobert1y@edublogs.org","dob":"2001-02-05","gender":"Female"},
{"id":72,"first_name":"Laureen","last_name":"Ninnoli","email":"lninnoli1z@shinystat.com","dob":"2003-01-18","gender":"Female"},
{"id":73,"first_name":"Hill","last_name":"Andrejs","email":"handrejs20@google.ru","dob":"2006-04-19","gender":"Male"},
{"id":74,"first_name":"Benni","last_name":"Strang","email":"bstrang21@apple.com","dob":"2001-02-11","gender":"Female"},
{"id":75,"first_name":"Valry","last_name":"Sellstrom","email":"vsellstrom22@dell.com","dob":"2001-10-27","gender":"Female"},
{"id":76,"first_name":"Kristi","last_name":"Wager","email":"kwager23@is.gd","dob":"2006-02-05","gender":"Female"},
{"id":77,"first_name":"Annemarie","last_name":"Stanley","email":"astanley24@miitbeian.gov.cn","dob":"2005-11-12","gender":"Female"},
{"id":78,"first_name":"Karlotte","last_name":"Jarley","email":"kjarley25@illinois.edu","dob":"2001-09-18","gender":"Female"},
{"id":79,"first_name":"Cleve","last_name":"Gamett","email":"cgamett26@boston.com","dob":"2003-08-14","gender":"Male"},
{"id":80,"first_name":"Cirillo","last_name":"Bonder","email":"cbonder27@nsw.gov.au","dob":"2002-10-09","gender":"Male"},
{"id":81,"first_name":"Kylila","last_name":"Snead","email":"ksnead28@admin.ch","dob":"2001-07-09","gender":"Female"},
{"id":82,"first_name":"Iseabal","last_name":"Conroy","email":"iconroy29@rakuten.co.jp","dob":"2003-05-18","gender":"Female"},
{"id":83,"first_name":"Conan","last_name":"Pelman","email":"cpelman2a@washington.edu","dob":"2006-04-13","gender":"Male"},
{"id":84,"first_name":"Cesaro","last_name":"Eitter","email":"ceitter2b@reuters.com","dob":"2002-04-27","gender":"Male"},
{"id":85,"first_name":"Stesha","last_name":"Strotone","email":"sstrotone2c@answers.com","dob":"2003-08-06","gender":"Female"},
{"id":86,"first_name":"Gonzales","last_name":"Dibnah","email":"gdibnah2d@cafepress.com","dob":"2006-06-01","gender":"Male"},
{"id":87,"first_name":"Bobette","last_name":"Versey","email":"bversey2e@pbs.org","dob":"2005-11-06","gender":"Female"},
{"id":88,"first_name":"Seka","last_name":"Pinnigar","email":"spinnigar2f@hp.com","dob":"2005-02-15","gender":"Female"},
{"id":89,"first_name":"Maryl","last_name":"Dendle","email":"mdendle2g@addtoany.com","dob":"2001-04-10","gender":"Female"},
{"id":90,"first_name":"Timoteo","last_name":"Wilbor","email":"twilbor2h@scientificamerican.com","dob":"2002-10-27","gender":"Male"},
{"id":91,"first_name":"Hayward","last_name":"Millican","email":"hmillican2i@theatlantic.com","dob":"2001-06-05","gender":"Male"},
{"id":92,"first_name":"Kaylil","last_name":"Noell","email":"knoell2j@who.int","dob":"2006-10-10","gender":"Female"},
{"id":93,"first_name":"Dyan","last_name":"Wenman","email":"dwenman2k@wp.com","dob":"2004-06-17","gender":"Female"},
{"id":94,"first_name":"Dew","last_name":"Allmark","email":"dallmark2l@hatena.ne.jp","dob":"2002-08-07","gender":"Male"},
{"id":95,"first_name":"Erich","last_name":"O'Hdirscoll","email":"eohdirscoll2m@eventbrite.com","dob":"2001-12-26","gender":"Male"},
{"id":96,"first_name":"Rollie","last_name":"Harpham","email":"rharpham2n@wikimedia.org","dob":"2003-09-09","gender":"Male"},
{"id":97,"first_name":"Jaquith","last_name":"Shawyers","email":"jshawyers2o@technorati.com","dob":"2002-03-07","gender":"Female"},
{"id":98,"first_name":"Freeland","last_name":"Ebunoluwa","email":"febunoluwa2p@homestead.com","dob":"2005-01-08","gender":"Male"},
{"id":99,"first_name":"Malorie","last_name":"Marrian","email":"mmarrian2q@posterous.com","dob":"2006-06-22","gender":"Female"},
{"id":100,"first_name":"Lindsay","last_name":"Reedie","email":"lreedie2r@disqus.com","dob":"2003-08-27","gender":"Male"}]

        for s in students:
            student = Student(**s)
            student.save()
        self.stdout.write(self.style.SUCCESS('Successfully populated students'))

        print("Populated successfully")